[package]
name = "recurdates"
version = "0.3.1"
authors = ["collodi <wkim149@gmail.com>"]
license = "MIT"
description = "A library for calculating dates for recurring events."

[dependencies]
serde = "1.0.24"
serde_derive = "1.0.24"
chrono = { version = "0.4.0", features = ["serde"] }
